[package]
name = "groestlcoin"
version = "0.21.0"
authors = ["Groestlcoin Developers <groestlcoin@gmail.com>"]
license = "CC0-1.0"
homepage = "https://github.com/Groestlcoin/rust-groestlcoin/"
repository = "https://github.com/Groestlcoin/rust-groestlcoin/"
documentation = "https://docs.rs/groestlcoin/"
description = "General groestlcoin library for using and interoperating with Groestlcoin."
keywords = [ "crypto", "groestlcoin" ]
readme = "README.md"

[lib]
name = "groestlcoin"
path = "src/lib.rs"

[features]
fuzztarget = ["secp256k1/fuzztarget", "groestlcoin_hashes/fuzztarget"]
unstable = []
use-serde = ["serde", "groestlcoin_hashes/serde"]

[dependencies]
bech32 = "0.7.1"
byteorder = "1.2"
groestlcoin_hashes = "0.7.4"
groestlcoinconsensus = { version = "2.19.1", optional = true }

serde = { version = "1", optional = true }
secp256k1 = "0.15"
hex = "=0.3.2"

[dev-dependencies]
serde_derive = "<1.0.99"
serde_json = "1"
serde_test = "1"
secp256k1 = { version = "0.15", features = ["rand"] }
