[package]
name = "groestlcoin"
version = "0.23.0"
authors = ["Groestlcoin Developers <groestlcoin@gmail.com>", "Andrew Poelstra <apoelstra@wpsoftware.net>"]
license = "CC0-1.0"
homepage = "https://github.com/Groestlcoin/rust-groestlcoin/"
repository = "https://github.com/Groestlcoin/rust-groestlcoin/"
documentation = "https://docs.rs/groestlcoin/"
description = "General groestlcoin library for using and interoperating with Groestlcoin."
keywords = [ "crypto", "groestlcoin" ]
readme = "README.md"

[lib]
name = "groestlcoin"
path = "src/lib.rs"

[features]
fuzztarget = ["secp256k1/fuzztarget", "groestlcoin_hashes/fuzztarget"]
unstable = []
rand = ["secp256k1/rand-std"]
use-serde = ["hex", "serde", "groestlcoin_hashes/serde", "secp256k1/serde"]

[dependencies]
bech32 = "0.7.2"
groestlcoin_hashes = { git = "https://github.com/Groestlcoin/groestlcoin_hashes", tag = "0.7.4-grs" }

secp256k1 = "0.17.1"

bitcoinconsensus = {  git = "https://github.com/Groestlcoin/rust-groestlcoinconsensus.git", version = "0.19.0-1", optional = true }
serde = { version = "1", optional = true }
hex = { version = "=0.3.2", optional = true }

[dev-dependencies]
hex = "=0.3.2"
serde_derive = "<1.0.99"
serde_json = "1"
serde_test = "1"
secp256k1 = { version = "0.17.1", features = ["rand-std"] }
